// <auto-generated />
namespace pampasoft6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class borra_campo_fecha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(borra_campo_fecha));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061159450_borra_campo_fecha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
